'use strict';

// =============================================================================
// Blustream model definitions (capabilities + state-shape flags), extracted so
// they can be required without pulling in @iobroker/adapter-core (used by both
// main.js and the status-parser unit tests). The trailing loop normalises defs
// (auto-generates the HDMI-N inputs map from inputCount; enables hasEDID for
// crosspoint matrices). See CLAUDE.md for what each flag drives.
// =============================================================================

// Model definitions with their capabilities and states
const MODEL_DEFINITIONS = {
    // AMF Series - Advanced Multi-Format
    amf42au: {
        name: 'AMF42AU',
        description: '4x2 Advanced Multi-Format Switcher',
        category: 'AMF',
        hasNetwork: true,
        hasBeep: false,
        hasDebug: false,
        hasMicrophone: true,
        hasAutoSwitch: true,
        hasOutputEnable: false,
        hasVideoMute: true,
        hasCEC: true,
        hasPresets: true,
        hasPictureControl: true,
        hasHDBT: true,
        hasPOC: true,
        hasNoSignalStandby: true,
        volumeMax: 100,
        outputs: 2,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDMI 4',
        },
        resolutions: {
            '00': '1024x768@60Hz',
            '01': '1280x800@60Hz',
            '02': '1360x768@60Hz',
            '03': '1440x900@60Hz',
            '04': '1680x1050@60Hz',
            '05': '1920x1200@60Hz',
            '06': '720P@50Hz',
            '07': '720P@60Hz',
            '08': '1080P@50Hz',
            '09': '1080P@60Hz',
            10: '4K2K@30Hz',
            11: '4K2K@50Hz',
            12: '4K2K@60Hz',
        },
        audioMixModes: {
            '01': 'HDMI Audio Only',
            '02': 'Mic Audio Only',
            '03': 'AUDEMBED Audio Only',
            '04': 'HDMI + Mic',
            '05': 'AUDEMBED + Mic',
        },
    },
    // MFP Series - Multi-Format Presentation
    mfp62: {
        name: 'MFP62',
        description: '6x2 4K Presentation Switcher',
        category: 'MFP',
        hasNetwork: true,
        hasBeep: false,
        hasDebug: false,
        hasMicrophone: true,
        hasAutoSwitch: true,
        hasOutputEnable: true,
        volumeMax: 100,
        outputs: 2,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'DisplayPort',
            '05': 'USB-C',
            '06': 'VGA',
        },
        resolutions: {
            '00': '1024x768@60Hz',
            '01': '1280x800@60Hz',
            '02': '1360x768@60Hz',
            '03': '1440x900@60Hz',
            '04': '1680x1050@60Hz',
            '05': '1920x1200@60Hz',
            '06': '720P@50Hz',
            '07': '720P@60Hz',
            '08': '1080P@50Hz',
            '09': '1080P@60Hz',
            10: '4K2K@25Hz',
            11: '4K2K@30Hz',
            12: '4K2K@50Hz',
            13: '4K2K@60Hz',
            14: 'DCI 4K2K@25Hz',
            15: 'DCI 4K2K@30Hz',
            16: 'DCI 4K2K@50Hz',
            17: 'DCI 4K2K@60Hz',
            18: 'Auto',
        },
        audioInputs: ['01', '02', '03', '04', '05'], // HDMI1, HDMI2, HDMI3, DP, USB-C
    },
    mfp72: {
        name: 'MFP72',
        description: '4x2 Presentation Switcher',
        category: 'MFP',
        hasNetwork: false,
        hasBeep: true,
        hasDebug: true,
        hasMicrophone: false,
        hasAutoSwitch: false,
        hasOutputEnable: false,
        volumeMax: 30,
        outputs: 2,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDMI 4',
        },
        output2ExtraInputs: {
            AV: 'AV',
            YPBPR: 'Component',
            VGA: 'VGA',
        },
        resolutions: {
            '01': '1080P@50Hz',
            '02': '1080P@60Hz',
            '03': '720P@50Hz',
            '04': '720P@60Hz',
            '05': '1280x1024@60Hz',
            '06': '1024x768@60Hz',
            '07': '1360x768@60Hz',
            '08': '1440x900@60Hz',
            '09': '1680x1050@60Hz',
        },
        hasAspectRatio: true,
        hasZoom: true,
        hasOverscan: true,
    },
    mfp112: {
        name: 'MFP112',
        description: '5x2 Presentation Switcher with HDBaseT',
        category: 'MFP',
        hasNetwork: true, // Has built-in TCP port 8000
        hasBeep: true,
        hasDebug: true,
        hasMicrophone: false,
        hasAutoSwitch: false,
        hasOutputEnable: true,
        hasHDBaseT: true,
        hasBypass: true,
        hasIR232: true,
        hasPerInputAudio: true,
        volumeMax: 30,
        outputs: 2,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDMI 4',
            HDBT: 'HDBaseT',
        },
        output2ExtraInputs: {
            AV: 'AV',
            YPBPR: 'Component',
            VGA1: 'VGA 1',
            VGA2: 'VGA 2',
            VGA3: 'VGA 3',
            VGA4: 'VGA 4',
        },
        resolutions: {
            '01': '1080P@50Hz',
            '02': '1080P@60Hz',
            '03': '720P@50Hz',
            '04': '720P@60Hz',
            '05': '1280x1024@60Hz',
            '06': '1024x768@60Hz',
            '07': '1360x768@60Hz',
            '08': '1440x900@60Hz',
            '09': '1680x1050@60Hz',
        },
        hasAspectRatio: true,
        hasZoom: true,
        hasOverscan: true,
    },
    // WMF Series - Wireless Media
    wmf51: {
        name: 'WMF51',
        description: 'Wireless Media Presenter',
        category: 'WMF',
        hasNetwork: true,
        hasWifi: true,
        hasBeep: false,
        hasDebug: false,
        hasMicrophone: false,
        hasAutoSwitch: false,
        hasOutputEnable: false,
        hasVideoMute: true,
        hasMultiview: true,
        hasStandby: true,
        hasSidebar: true,
        isWireless: true,
        volumeMax: 100,
        outputs: 1,
        inputs: {}, // Wireless inputs - dynamic
        resolutions: {
            '00': 'Auto',
            '01': '720P@50Hz',
            '02': '720P@60Hz',
            '03': '1080P@30Hz',
            '04': '1080P@50Hz',
            '05': '1080P@60Hz',
            '06': '4K@30Hz',
            '07': '4K@50Hz',
            '08': '4K@60Hz',
        },
        dualLAN: true,
    },
    wmf72: {
        name: 'WMF72',
        description: 'Wireless Media Presenter with Dual Display',
        category: 'WMF',
        hasNetwork: true,
        hasWifi: true,
        hasBeep: false,
        hasDebug: false,
        hasMicrophone: false,
        hasAutoSwitch: true,
        hasOutputEnable: false,
        hasVideoMute: true,
        hasMultiview: true,
        hasStandby: true,
        hasSidebar: true,
        hasDualDisplay: true,
        hasDisplayModes: true,
        hasLayouts: true,
        hasAudioModes: true,
        hasSecurity: true,
        hasUSBControl: true,
        isWireless: true,
        volumeMax: 100,
        outputs: 2,
        inputs: {}, // Wireless inputs - dynamic
        resolutions: {
            '00': 'Auto',
            '01': '720P@50Hz',
            '02': '720P@60Hz',
            '03': '1080P@30Hz',
            '04': '1080P@50Hz',
            '05': '1080P@60Hz',
            '06': '3840x2160@30Hz',
            '07': '3840x2160@50Hz',
            '08': '3840x2160@60Hz',
            '09': '4096x2160@30Hz',
            10: '4096x2160@50Hz',
            11: '4096x2160@60Hz',
        },
        displayModes: {
            1: 'Mirroring',
            2: 'Multiview + Single',
            3: 'Single + Multiview',
        },
        layouts: {
            '01': 'Single',
            '02': 'Dual',
            '03': 'Triple-T',
            '04': 'Triple-L',
            '05': 'Triple-B',
            '06': 'Triple-R',
            '07': 'Quad',
            '08': 'Quad-B',
            '09': 'Quad-R',
            10: 'Quad-T',
            11: 'Quad-L',
        },
        audioModes: {
            '01': 'Audio Mixer',
            '02': 'Single Input Source',
            '03': 'Single Input Window',
            '04': 'First IN',
            '05': 'Last IN',
        },
        dualLAN: true,
    },
    // C Series - Contractor HDBaseT Matrix (crosspoint, non-scaling)
    c66: {
        name: 'C66',
        description: '6x6 HDBaseT Matrix',
        category: 'C',
        isMatrix: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 6,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDMI 4',
            '05': 'HDMI 5',
            '06': 'HDMI 6',
        },
    },
    c88: {
        name: 'C88',
        description: '8x8 HDBaseT Matrix',
        category: 'C',
        isMatrix: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDMI 4',
            '05': 'HDMI 5',
            '06': 'HDMI 6',
            '07': 'HDMI 7',
            '08': 'HDMI 8',
        },
    },

    // =========================================================================
    // Expanded range (v0.6.0). Most models below are crosspoint matrices/switches
    // that reuse the isMatrix routing path. `inputCount` auto-generates an
    // "HDMI N" inputs map (see normalisation loop after this object). Command
    // dialect: default "spaced" (OUT xx FR yy); CMX/MX HDMI matrices and SW-AB
    // switchers set commandStyle 'nospace' (OUT01FR04) per their manuals. PoC
    // verb via pocCommand (POCOUT default | 'POC OUT' | 'POC TX'). Core routing
    // is command-doc verified; audio-breakout/ARC/CEC/EDID are flagged for a
    // later pass (see MODEL-EXPANSION-PLAN.md / CLAUDE.md TODO).
    // -------------------------------------------------------------------------

    // --- C Series (Contractor HDBaseT), spaced, POCOUT ---
    c44kit: {
        name: 'C44-KIT',
        description: '4x4 HDBaseT Matrix (legacy)',
        category: 'C',
        isMatrix: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 4,
        inputCount: 4,
    },
    c44cs: {
        name: 'C44CS-KIT',
        description: '4x4 HDBaseT CSC Matrix',
        category: 'C',
        isMatrix: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 4,
        inputCount: 4,
    },
    c66cs: {
        name: 'C66CS',
        description: '6x6 HDBaseT CSC Matrix',
        category: 'C',
        isMatrix: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 6,
        inputCount: 6,
    },
    c88cs: {
        name: 'C88CS',
        description: '8x8 HDBaseT CSC Matrix',
        category: 'C',
        isMatrix: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- HMXL Series (Standard HDBaseT), spaced, POCOUT ---
    hmxl42arc: {
        name: 'HMXL42ARC-KIT',
        description: '4x2 HDBaseT CSC Matrix with ARC',
        category: 'HMXL',
        isMatrix: true,
        hasCSC: true,
        hasARC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 2,
        inputCount: 4,
    },
    hmxl44cs: {
        name: 'HMXL44CS-KIT',
        description: '4x4 HDBaseT CSC Matrix',
        category: 'HMXL',
        isMatrix: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 4,
        inputCount: 4,
    },
    hmxl44arc: {
        name: 'HMXL44ARC-KIT',
        description: '4x4 HDBaseT Matrix with ARC',
        category: 'HMXL',
        isMatrix: true,
        hasCSC: true,
        hasARC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 4,
        inputCount: 4,
    },
    hmxl66arc: {
        name: 'HMXL66ARC',
        description: '6x6 HDBaseT Matrix with ARC',
        category: 'HMXL',
        isMatrix: true,
        hasCSC: true,
        hasARC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 6,
        inputCount: 6,
    },
    hmxl88arc: {
        name: 'HMXL88ARC',
        description: '8x8 HDBaseT Matrix with ARC',
        category: 'HMXL',
        isMatrix: true,
        hasCSC: true,
        hasARC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },
    hmxl88v2: {
        name: 'HMXL88-V2',
        description: '8x8 HDBaseT Matrix (legacy)',
        category: 'HMXL',
        isMatrix: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- HMX 18G Series (HDBaseT 3.0), spaced, POCOUT ---
    hmx44_18g: {
        name: 'HMX44-18G-KIT',
        description: '4x4 HDBaseT 3.0 (18G) Matrix',
        category: 'HMX',
        isMatrix: true,
        hasCECActions: true,
        hasAudioMatrix: true,
        hasHDBT3: true,
        hasARC: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 4,
        inputCount: 4,
    },
    hmx88_18g: {
        name: 'HMX88-18G',
        description: '8x8 HDBaseT 3.0 (18G) Matrix',
        category: 'HMX',
        isMatrix: true,
        hasCECActions: true,
        hasAudioMatrix: true,
        hasHDBT3: true,
        hasARC: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- PLA (Platinum) Series, spaced, POCOUT ---
    pla88cs: {
        name: 'PLA88CS',
        description: '8x8 HDBaseT CSC Matrix (simultaneous HDMI)',
        category: 'PLA',
        isMatrix: true,
        hasCSC: true,
        simulHDMI: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },
    pla88arc: {
        name: 'PLA88ARC-V2',
        description: '8x8 HDBaseT Matrix with ARC',
        category: 'PLA',
        isMatrix: true,
        hasARC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },
    pla88l: {
        name: 'PLA88L-V2',
        description: '8x8 HDBaseT Lite Matrix',
        category: 'PLA',
        isMatrix: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- Pro Matrix Series, spaced, PoC verb is "POC TX" ---
    pro48hbt: {
        name: 'PRO48HBT70',
        description: '4x8 HDBaseT Matrix (legacy)',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 8,
        inputCount: 4,
    },
    pro48hbtcs: {
        name: 'PRO48HBT70CS',
        description: '4x8 HDBaseT CSC Matrix',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 8,
        inputCount: 4,
    },
    pro88hbtcs: {
        name: 'PRO88HBT70CS',
        description: '8x8 HDBaseT CSC Matrix',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },
    pro88hdmi: {
        name: 'PRO88HDMI-V2',
        description: '8x8 HDMI Matrix',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- CMX Series (HDMI matrices), nospace, no PoC, audio breakout ---
    cmx42cs: {
        name: 'CMX42CS',
        description: '4x2 HDMI CSC Matrix',
        category: 'CMX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasCSC: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 2,
        inputCount: 4,
    },
    cmx44cs: {
        name: 'CMX44CS-V2',
        description: '4x4 HDMI CSC Matrix',
        category: 'CMX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasCSC: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 4,
        inputCount: 4,
    },
    cmx44ab: {
        name: 'CMX44AB',
        description: '4x4 HDMI Matrix with Audio Breakout',
        category: 'CMX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 4,
        inputCount: 4,
    },
    cmx88cs: {
        name: 'CMX88CS',
        description: '8x8 HDMI CSC Matrix',
        category: 'CMX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 8,
        inputCount: 8,
    },
    cmx88ab: {
        name: 'CMX88AB',
        description: '8x8 HDMI Matrix with Audio Breakout',
        category: 'CMX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        outputs: 8,
        inputCount: 8,
    },

    // --- MX Series (HDMI matrices), nospace, audio breakout ---
    mx22ab8k: {
        name: 'MX22AB-8K',
        description: '2x2 8K HDMI 2.1 Matrix with Audio Breakout',
        category: 'MX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        outputs: 2,
        inputCount: 2,
    },
    mx44abv2: {
        name: 'MX44AB-V2',
        description: '4x4 HDMI Matrix with Audio Breakout',
        category: 'MX',
        isMatrix: true,
        commandStyle: 'nospace',
        hasAudioBreakout: true,
        hasNetwork: true,
        hasOutputEnable: true,
        outputs: 4,
        inputCount: 4,
    },

    // --- SW Series (basic HDMI/HDBaseT switchers), single output ---
    sw41hdbt: {
        name: 'SW41HDBT',
        description: '4-Way HDBaseT/HDMI Input Switch',
        category: 'SW',
        isMatrix: true,
        hasCECActions: true,
        hasNetwork: true,
        hasPOC: true,
        pocCommand: 'POC OUT',
        hasHDBT: true,
        outputs: 1,
        inputs: {
            '01': 'HDMI 1',
            '02': 'HDMI 2',
            '03': 'HDMI 3',
            '04': 'HDBaseT',
        },
    },
    sw41abv2: {
        name: 'SW41AB-V2',
        description: '4-Way 4K HDMI Switch with Audio Breakout',
        category: 'SW',
        isMatrix: true,
        commandStyle: 'nospace',
        noOutputIndex: true,
        hasAutoSwitch: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        outputs: 1,
        inputCount: 4,
    },
    sw41ab8k: {
        name: 'SW41AB-8K',
        description: '4-Way 8K HDMI Switch',
        category: 'SW',
        isMatrix: true,
        commandStyle: 'nospace',
        noOutputIndex: true,
        hasAutoSwitch: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        outputs: 1,
        inputCount: 4,
    },
    sw42da: {
        name: 'SW42DA',
        description: '4-Way HDMI Switch with Dante',
        category: 'SW',
        isMatrix: true,
        commandStyle: 'nospace',
        noOutputIndex: true,
        hasAutoSwitch: true,
        hasDanteDsp: true, // Dante/audio-DSP STATUS telemetry (master vol/mute/ARC) — read-only
        hasNetwork: true,
        // Single routing selection (switch, not matrix). The -V2 STATUS shows a 2nd
        // output row, but it is a scaled/downmix follower of the same selected input,
        // not an independently-routable output — so outputs stays 1.
        outputs: 1,
        inputCount: 4,
    },
    sw21abv2: {
        name: 'SW21AB-V2',
        description: '2-Way 4K HDMI Switch with Audio Breakout',
        category: 'SW',
        isMatrix: true,
        commandStyle: 'nospace',
        noOutputIndex: true,
        hasAutoSwitch: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        outputs: 1,
        inputCount: 2,
    },
    sw21abv3: {
        name: 'SW21AB-V3',
        description: '2-Way 4K HDMI 2.0 Switch with Audio Breakout',
        category: 'SW',
        isMatrix: true,
        commandStyle: 'nospace',
        noOutputIndex: true,
        hasAutoSwitch: true,
        hasAudioBreakout: true,
        hasNetwork: true,
        outputs: 1,
        inputCount: 2,
    },

    // --- Phase 2: 16x16 + modular Pro Matrix (spaced, POC TX) ---
    pro16hbtcs: {
        name: 'PRO16HBT70CS',
        description: '16x16 HDBaseT CSC Matrix',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        hasCSC: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 16,
        inputCount: 16,
    },
    custompro: {
        name: 'CUSTOMPRO-HUB',
        description: 'Custom Pro Modular Matrix (up to 8x8)',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        configurableIO: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 8,
        inputCount: 8,
    },
    custompro16: {
        name: 'CUSTOMPRO-HUB16',
        description: 'Custom Pro Modular Matrix (up to 16x16)',
        category: 'PRO',
        isMatrix: true,
        hasAudioEmbed: true,
        configurableIO: true,
        hasNetwork: true,
        hasOutputEnable: true,
        hasPresets: true,
        hasPOC: true,
        pocCommand: 'POC TX',
        hasHDBT: true,
        outputs: 16,
        inputCount: 16,
    },

    // --- Phase 4: Video-wall / multi-view processors (spaced, OUT MODE ...) ---
    // Matrix-mode + multi-view-window routing reuse output.N.source; videowall.*
    // + input.N.type add mode/VW-source/bezel/MV-audio/input-signal-type.
    mx44vw: {
        name: 'MX44VW',
        description: '4x4 HDMI/VGA Seamless Matrix / Video Wall / Multi-View',
        category: 'MX',
        isMatrix: true,
        hasVideoWall: true,
        hasVGAInputs: true,
        hasNetwork: true,
        hasOutputEnable: true,
        outputs: 4,
        inputs: { '01': 'Input 1', '02': 'Input 2', '03': 'Input 3', '04': 'Input 4' },
    },
    mx44avw: {
        name: 'MX44AVW',
        description: '4x4 Advanced Video Wall Processor (PIP/POP, rotation)',
        category: 'MX',
        isMatrix: true,
        hasVideoWall: true,
        hasVGAInputs: true,
        hasNetwork: true,
        hasOutputEnable: true,
        outputs: 4,
        inputs: { '01': 'Input 1', '02': 'Input 2', '03': 'Input 3', '04': 'Input 4' },
    },
    mv41: {
        name: 'MV41',
        description: '4-Way Multi-View HDMI Switcher',
        category: 'MX',
        isMatrix: true,
        hasVideoWall: true,
        hasNetwork: true,
        outputs: 1,
        inputCount: 4,
    },

    // --- Phase 4: USB / KVM matrix (spaced, routes USB via "USBOUT xx FR yy") ---
    mx44kvm: {
        name: 'MX44KVM',
        description: '4x4 USB 3.0 KVM Matrix',
        category: 'MX',
        isMatrix: true,
        routePrefix: 'USBOUT',
        noAllSource: true,
        hasNetwork: true,
        hasPresets: true,
        outputs: 4,
        inputs: {
            '01': 'USB Device 1',
            '02': 'USB Device 2',
            '03': 'USB Device 3',
            '04': 'USB Device 4',
        },
    },
};

// Normalise defs: generate an "HDMI N" inputs map from `inputCount` where an
// explicit `inputs` object was not supplied. Keeps the large matrix defs terse.
for (const def of Object.values(MODEL_DEFINITIONS)) {
    if (!def.inputs && def.inputCount) {
        def.inputs = {};
        for (let i = 1; i <= def.inputCount; i++) {
            def.inputs[String(i).padStart(2, '0')] = `HDMI ${i}`;
        }
    }
    // EDID management (EDID xx DF zz / EDID xx CP yy) is universal Blustream matrix
    // syntax. Enable it for every crosspoint matrix except the USB/KVM matrix
    // (routePrefix) and the basic single-output SW-AB switches (noOutputIndex),
    // whose EDID handling is not the same. Explicit hasEDID:false wins.
    if (def.hasEDID === undefined && def.isMatrix && !def.routePrefix && !def.noOutputIndex) {
        def.hasEDID = true;
    }
}

module.exports = { MODEL_DEFINITIONS };
